B::B() called
... catched
exit 0
